server:
  port: 9090


#data source
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: root #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/filemgt?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB





#mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.saferfilemanager.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



#Authorization
authorization:
  path2role:
    /admin/showAllUsers: ADMIN
    /admin/addUser: ADMIN
    /admin/deleteUser: ADMIN
    /admin/updateUser: ADMIN
    /file/selectAll: USER
    /file/upload: USER
    /file/download: USER
    /file/delete: USER
    /share/addShare: USER
    /share/download: USER



